# -*- coding: utf-8 -*-
"""Aula - 071025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJJo8qv9zXSKDBD0GrxNTmiAFh8POWgm

**Importando as dependências**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""**Carregando o dataset**"""

df = pd.read_csv('train_and_test2.csv')

"""**Corrigindo o nome da coluna**"""

if '2urvived' in df.columns:
  df.rename(columns={'2urvived': 'Survived'}, inplace=True)

"""**Limpar as colunas/variáveis desnecessárias**"""

df = df.loc[:, ~df.columns.str.startswith('zero')]
print(df)

"""**Selecionar apenas colunas úteis**"""

cols_interesse = ['Age', 'Fare', 'Sex', 'sibsp', 'Parch', 'Pclass', 'Embarked', 'Survived']
df = df[[c for c in cols_interesse if c in df.columns]]
print(df)

"""**Calcular a correlação entre as variáveis**"""

corr = df.corr(numeric_only=True)

"""**Plotando o gráfico**"""

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.show()