# -*- coding: utf-8 -*-
"""Aula - 120825.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDzNCLtl6DGSxiAs_kg2nrv6fbIChL6O

**Primeiro programa criado com Python**
"""

#Importando as bibliotecas que serão utilizadas

import random

"""Criando minha ***POPULAÇÃO***, uma lista com todos os elementos"""

populacao = list(range(1, 101))

"""Exibindo a população criada"""

print("População: ")
print(populacao)

"""Definindo o tamanho (k) da amostra"""

tamanho_amostra = 10

"""Extraindo uma amostra **ALEATÓRIA** da população"""

amostra = random.sample(populacao, tamanho_amostra)

print("Exibindo 10 elementos como amostra \n")
print(amostra)

"""**Aula 03 - Estatística Descritiva**"""

import statistics

"""*1º Exemplo - Média*"""

dados = [2, 5, 8, 3, 6]
print(dados)

media = statistics.mean(dados)
print("A Média é: ",media)

"""*2º Exemplo - Mediana*"""

mediana = statistics.median(dados)
print(mediana)

3º Exemplo - Moda

novo_dados = [2, 5, 8, 3, 5, 6, 5]
moda = statistics.mode(novo_dados)
print("A Moda é: ", moda)

"""*4º Exemplo - Variância*"""

variancia = statistics.variance(novo_dados)
print("A Variância é: ", variancia)

"""*5º Exemplo - Desvio Padrão*"""

desvio_padrao = statistics.stdev(novo_dados)
print("O Desvio Padrão é: ", desvio_padrao)

"""*6º Exemplo - Amplitude*"""

amplitude = max(novo_dados) - min(novo_dados)
print("A Amplitude é de: ", amplitude)

"""*7º Exemplo - Salários*"""

salarios = [2000, 2100, 2000, 2050, 1995, 2000, 80000]
media_salarial = statistics.mean(salarios)
print("A Média salarial é de: ", media_salarial)
desvio_padrao_salarial = statistics.stdev(salarios)
print("O Desvio Padrão dos Salários é de: ", desvio_padrao_salarial)
mediana_salarial = statistics.median(salarios)
print("A Mediana salarial é de: ", mediana_salarial)