# -*- coding: utf-8 -*-
"""Aula04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtCKRcKf3iq3jph3-GqygCz6fSM9k_73
"""

import numpy as np
import matplotlib.pyplot as plt

"""**Gerando dados simulando uma distribuição normal**"""

mu, sigma = 0, 0.1 #Média e desvio padrão

dados = np.random.normal(mu, sigma, 1000)
print(dados)

plt.figure(figsize=(8,6))
plt.hist(dados, bins=10, density=True, alpha=0.6, color='g')