# -*- coding: utf-8 -*-
"""Cópia de Aula - 111125.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Fvpn9_crKX70qLuomFapdxoFMDpKcxH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importando somente o que vou utilizar
from sklearn.cluster import KMeans

"""Criando a Base de Dados"""

#Garante a reprodutibilidade do código - Garante dados iguais
np.random.seed(42)

#Grupo 1: Baixa Renda, baixo gasto
grupo1 = np.random.normal(loc=[2000, 500], scale=[300, 80], size=[50, 2])

#Grupo 2: Média renda, médio gasto
grupo2 = np.random.normal(loc=[5000, 2000], scale=[400, 150], size=[50, 2])

#Grupo 3: Alta renda, alto gasto
grupo3 = np.random.normal(loc=[9000, 3500], scale=[500, 200], size=[50, 2])

#Agrupamento de Arrays em uma tabela
dados = np.vstack([grupo1, grupo2, grupo3])

#Criando um DataFrame com os dados agrupados
df = pd.DataFrame(dados, columns=["renda_mensal", "gasto_mensal"])

df.head()

"""Visualizar os dados antes do KMeans"""

plt.figure(figsize=[6, 4])
plt.scatter(df["renda_mensal"], df["gasto_mensal"])
plt.xlabel("Renda Mensal (R$)")
plt.ylabel("Gasto Mensal (R$)")
plt.title("Clientes (Sem Cluster)")
plt.show()

"""Aplicando o K_Means"""

#Definindo o número total de Clusters

k = 3

#Configurando o algoritmo KMeans
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)

#Clusterizando os dados
kmeans.fit(df)

#Rótulo (cluster) de cada ponto
labels = kmeans.labels_

#centroids
centroides = kmeans.cluster_centers_

"""Visualizando os clusters"""

plt.figure(figsize=(6, 4))

#Plotando cada cluster com uma cor diferente
for cluster_id in range(k):
  cluster_points = df[labels == cluster_id]
  plt.scatter(
      cluster_points["renda_mensal"],
      cluster_points["gasto_mensal"],
      label=f"Cluster {cluster_id}",
  )

  #Plotando os centroids
  plt.scatter(
      centroides[:, 0],
      centroides[:, 1],
      s=200,
      marker="X",
      edgeColor="black",
      label="Centroides"
  )

  plt.legend()
  plt.show()

