# -*- coding: utf-8 -*-
"""Aula020925.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFHCyhvUdakebcdQTmjswGSK3YdrzCsX
"""



import numpy as np

#Criar o conjunto de dados de exemplo
# dados = np.array([2, 5, 7, 8, 10, 12, 15, 18, 20, 22])
dados = np.array([3, 5, 7, 8, 12, 13, 14, 18, 21])

#Calculando os quartis usando NumPy

Q1 = np.percentile(dados, 25)
print(Q1)
Q2 = np.percentile(dados, 50)
print(Q2)
Q3 = np.percentile(dados, 75)
print(Q3)

# Identificando possíveis outliters

IQR = Q3 - Q1
print("Valor do IQR: ", IQR)

limite_inferior = Q1 - 1.5 * IQR
print("Limite Inferior: ", limite_inferior)

limite_superior = Q3 + 1.5 * IQR
print("Limite superior: ", limite_superior)

#Fazendo um laço (for) no array dados, filtrando valores menor que limite_inferior
# e maior que limite superior, vinculando esses elementos filtrados na variável
# outlier

outliers = [x for x in dados if x < limite_inferior or x > limite_superior]

if outliers:
  print("Possíveis Outliers: ", outliers)
else:
  print("Não foram encontrados possíveis outliers.")

import matplotlib.pyplot as plt

# Gerar dados aleatórios para o exemplo

np.random.seed(10)
base = np.random.normal(100 , 20, 200)
#print(base)

#Criar o BoxPlot

plt.figure(figsize=(8, 6))
plt.boxplot(base, showmeans=True, vert=True, patch_artist=True)

#Configurar o gráfico

plt.title("Exemplo de BoxPlot")
plt.xlabel("Valores")
plt.show()