# -*- coding: utf-8 -*-
"""Aula - 120825.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDzNCLtl6DGSxiAs_kg2nrv6fbIChL6O

**Primeiro programa criado com Python**
"""

#Importando as bibliotecas que serão utilizadas

import random

"""Criando minha ***POPULAÇÃO***, uma lista com todos os elementos"""

populacao = list(range(1, 101))

"""Exibindo a população criada"""

print("População: ")
print(populacao)


"""Definindo o tamanho (k) da amostra"""

tamanho_amostra = 10

"""Extraindo uma amostra **ALEATÓRIA** da população"""

amostra = random.sample(populacao, tamanho_amostra)

print('\n')
print("Exibindo 10 elementos como amostra: ")
print(amostra)
