# -*- coding: utf-8 -*-
"""Aula160925.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MA7BeCOmDJNViN_DqYNepW5GJ_jTnXT
"""

import numpy as np
from scipy import stats

#Dados ficticios notas de alunos antes e depois do método

antes = [6.5, 7.0, 6.8, 7.2, 6.9]
depois = [7.8, 8.0, 7.5, 8.3, 7.9]

#Teste t para duas amostras independentes

t_stat, p_value = stats.ttest_ind(antes, depois)

print("Estatística t: ", t_stat)
print("p-value: ", p_value)

#Nível de significância

alpha = 0.05

if p_value < alpha:
  print("Rejeitamos H0: as médias são significativamente diferentes")
else:
  print("Não podemos rejeitar H0: não há diferenças significativas entre os métodos")